export default {
  en: {
    title: 'Please rate your impression of the robot on these scales',
    requiredMessage: 'You forgot this one!',
    submitText: 'submit',
    items: {
      i1: ['Fake', 'Natural'],
      i2: ['Machinelike', 'Humanlike'],
      i3: ['Unconscious', 'Conscious'],
      i4: ['Artificial', 'Lifelike'],
      i5: ['Moving rigidly', 'Moving elegantly'],
      ii1: ['Dead', 'Alive'],
      ii2: ['Stagnant', 'Lively'],
      ii3: ['Mechanical', 'Organic'],
      ii5: ['Inert', 'Interactive'],
      ii6: ['Apathetic', 'Responsive'],
      iii1: ['Dislike', 'Like'],
      iii2: ['Unfriendly', 'Friendly'],
      iii3: ['Unkind', 'Kind'],
      iii4: ['Unpleasant', 'Pleasant'],
      iii5: ['Awful', 'Nice'],
      iv1: ['Incompetent', 'Competent'],
      iv2: ['Ignorant', 'Knowledgeable'],
      iv3: ['Irresponsible', 'Responsible'],
      iv4: ['Unintelligent', 'Intelligent'],
      iv5: ['Foolish', 'Sensible'],
    },
  },
  fr: {
    title: 'Veuillez noter vos impressions au sujet du robot sur les échelles ci-dessous',
    requiredMessage: 'Vous avez oublié celui-ci!',
    submitText: 'soumettre',
    items: {
      i1: ['Faux', 'Naturel'],
      i2: ['D’aspect Machinale', 'D’aspect Humain'],
      i3: ['Inconscient', 'Conscient'],
      i4: ['Artificiel', 'Paraissant vivant'],
      i5: ['Bougeant avec rigidité', 'Bougeant avec fluidité'],
      ii1: ['Mort', 'Vivant'],
      ii2: ['Inanimé', 'Animé'],
      ii3: ['Mécanique', 'Organique'],
      ii5: ['Inert', 'Interactif'],
      ii6: ['Apathique', 'Attentif'],
      iii1: ['Déplaisant', 'Plaisant'],
      iii2: ['Inamical', 'Amical'],
      iii3: ['Malaimable', 'Aimable'],
      iii4: ['Désagreable', 'Agréable'],
      iii5: ['Horrible', 'Gentil'],
      iv1: ['Uncompétent', 'Compétent'],
      iv2: ['Ignorant', 'Cultivé'],
      iv3: ['Irresponsable', 'Responsable'],
      iv4: ['Inintelligent', 'Intelligent'],
      iv5: ['Insensé', 'Sensé'],
    },
  },
  de: {
    title: 'Bitte beurteilen sie Ihren Eindruck des Roboters auf diesen Skalen',
    requiredMessage: 'Du hast das vergessen!',
    submitText: 'senden',
    items: {
      i1: ['Unecht', 'Natürlich'],
      i2: ['Wie eine Maschine', 'Wie ein Mensch'],
      i3: ['Hat kein Bewusstsein', 'Hat ein Bewusstsein'],
      i4: ['Künstlich', 'Realistisch'],
      i5: ['Bewegt sich steif', 'Bewegt sich flüssig'],
      ii1: ['Tot', 'Lebendig'],
      ii2: ['Unbewegt', 'Lebendig'],
      ii3: ['Mechanisch', 'Organisch'],
      ii5: ['Träge', 'Interaktiv'],
      ii6: ['Apathisch', 'Reagierend'],
      iii1: ['Nicht mögen', 'Mögen'],
      iii2: ['Unfreundlich', 'Freundlich'],
      iii3: ['Unhöflich', 'Höflich'],
      iii4: ['Unangenehm', 'Angenehm'],
      iii5: ['Furchtbar', 'Nett'],
      iv1: ['Inkompetent', 'Kompetent'],
      iv2: ['Ungebildet', 'Unterrichtet'],
      iv3: ['Verantwortungslos', 'Verantwortungsbewusst'],
      iv4: ['Unintelligent', 'Intelligent'],
      iv5: ['Unvernünftig', 'Vernünftig'],
    },
  },
  es: {
    title: 'Por favor de su opinión del robot en los siguientes aspectos',
    requiredMessage: '¡Olvidaste este!',
    submitText: 'enviar',
    items: {
      i1: ['Falso', 'Natural'],
      i2: ['Con Aspecto de Máquina', 'Con Aspecto Humano'],
      i3: ['Inconsciente', 'Consciente'],
      i4: ['Artificial', 'Parece Vivo'],
      i5: ['Se Mueve Rígidamente', 'Se Mueve con Fluidez'],
      ii1: ['Muerto', 'Con Vida'],
      ii2: ['Inactivo', 'Vivaz'],
      ii3: ['Mecánico', 'Orgánico'],
      ii5: ['Estático', 'Interactivo'],
      ii6: ['Indiferente', 'Atento'],
      iii1: ['Disgusta', 'Gusta'],
      iii2: ['No Amigable', 'Amigable'],
      iii3: ['Descortés', 'Amable'],
      iii4: ['Desagradable', 'Agradable'],
      iii5: ['Feo', 'Lindo'],
      iv1: ['Incompetente', 'Competente'],
      iv2: ['Ignorante', 'Culto'],
      iv3: ['Irresponsable', 'Responsable'],
      iv4: ['Sin inteligencia', 'Inteligente'],
      iv5: ['Insensato', 'Juicioso'],
    },
  },
};
